### ISSUE TITLE
README refers to requirements.txt

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITKPythonPackage#11]
The build instructions in the README.md refer to a requirements.txt file, which does not exist. Only a requirements-dev.txt exists.

Which one is correct?

**Comment by jcfr** [comment]
Since `scikit-build` is only required to build the distributions (either souce or wheel), it should be in the `requirements-dev.txt`. IOW, there is no need to install scikit-build when installing the wheels.
