### ISSUE TITLE
Path is too long to build on windows

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITKPythonPackage#22]
Building on Windows I get the following error with Py3.5, VS14, no Ninja
>    Performing configure step for 'ITK'
>     Not searching for unused variables given on the command line.
>     loading initial cache file C:/d/p/_skbuild/cmake-build/SimpleITK-superbuild/ITK-build/CMakeCacheInit.txt
>     CMake Error at CMakeLists.txt:30 (message):
>       ITK source code directory path length is too long (52 > 50).Please move the
>       ITK source code directory to a directory with a shorter path.
> 

Cloning this repository into "C:\d\p" is a short path, but not short enough.

**Comment by jcfr** [comment]
We could have `C:/d/p/_skbuild/cmake-build/SimpleITK-superbuild/ITK-build` instead of `C:/d/p/_skbuild/cmake-build/SITK-superbuild/ITK-build`
