### ISSUE TITLE
On Windows Ninja generator builds in debug mode

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITKPythonPackage#25]
I am using Python 3.5, with scikit 0.5.1, CMake 3.7.1, and MSVC 14 2015 on Windows Server 12.

The "Visual Studio 14 2015 Win64" generator is correctly building in "Release" mode by default.

When the Ninja generator was used the SimpleITK sub-sub-project was build in debug mode. This resulting in very large libraries that would not link.

**Comment by jcfr** [comment]
Would this help: https://github.com/SimpleITK/SimpleITKPythonPackage/pull/26 ?

**Comment by jcfr** [comment]
Closing. Fix integrated in https://github.com/SimpleITK/SimpleITKPythonPackage/commit/54951ddf5a09212a2378365b84654d0f3793ab8c
