### ISSUE TITLE
Download error during build

### ISSUE THREAD

**Issue by gnthibault** [SimpleITK/SimpleITKPythonPackage#30]
I may be wrong, but I think that one of the target download is no longer valid:

CMake Error at /usr/local/share/cmake-3.8/Modules/ExternalData.cmake:1121 (message):
  

  Object MD5=2e115fe26e435e33b0d5c022e4490567 not found at:

    https://placid.nlm.nih.gov/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://simpleitk.github.io/SimpleITKExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=2e115fe26e435e33b0d5c022e4490567&algorithm=MD5 ("Unsupported protocol")
    https://insightsoftwareconsortium.github.io/ITKTestingData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")
    https://itk.org/files/ExternalData/MD5/2e115fe26e435e33b0d5c022e4490567 ("Unsupported protocol")

CMakeFiles/SuperBuildSimpleITKSourceReal.dir/build.make:63: recipe for target 'ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp' failed
make[5]: *** [ExternalData/.ExternalSource/lua-5.1.5.tar.gz-hash-stamp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SuperBuildSimpleITKSourceReal.dir/all' failed
make[4]: *** [CMakeFiles/SuperBuildSimpleITKSourceReal.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK-superbuild.dir/build.make:111: recipe for target 'SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build' failed
make[2]: *** [SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build] Error 2
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/SimpleITK-superbuild.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK-superbuild.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by blowekamp** [comment]
Hello,

Thanks for reporting the issue and trying out SimpleITKPythonPackaging.

This error message indicates that your cmake does not support HTTPS. As CMake appears to be in "/usr/local", I'll assume that you built CMake yourself. You need to set "CMAKE_USE_OPENSSL" to true when building CMake.

Alternatively, you could install CMake in you Python environment with "pip install CMake".

**Comment by gnthibault** [comment]
Thank you very much for your help, and sorry for the silly question!

**Comment by blowekamp** [comment]
I will add this issue to the FAQ as it has come up a couple times and it's not clear what the underlying problem is.

**Comment by jcfr** [comment]
On linux, you could simply run:

```
./scripts/dockcross-manylinux-build-wheels.sh
```

More details here: https://github.com/SimpleITK/SimpleITKPythonPackage#linux
