### ISSUE TITLE
N4 Correction Error (maybe bug in windows)

### ISSUE THREAD

**Issue by gourdchen** [SimpleITK/SimpleITKPythonPackage#40]
when I user N4BiasFieldCorrectionImageFilter to do the n4 correction,this error will randomly show, my code is the same as the example of SimpleITK. when I run it in linux  with the same data, it  never show the error. I think it maybe a bug in windows.
The InputImage_1 Origin of error message is not my mask's Origin, it maybe a unknown number.

   File "E:\Miniconda3\envs\brainTools\lib\site-packages\SimpleITK\SimpleITK.py", line 51747, in Execute
    return _SimpleITK.N4BiasFieldCorrectionImageFilter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleITK N4BiasFieldCorrectionImageFilter_Execute: c:\d\vs14-win64-pkg\simpleitk-build\itk-prefix\include\itk-4.13\itkImageToImageFilter.hxx:241:
itk::ERROR: SubtractImageFilter(0000018EBB7E22A0): Inputs do not occupy the same physical space!
InputImage Origin: [-9.0000000e+01, 1.2600000e+02, -7.2000000e+01], InputImage_1 Origin: [-4.5250000e+01, 5.4250000e+01, -4.5250000e+01]
        Tolerance: 1.0000000e-06
InputImage Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00], InputImage_1 Spacing: [4.5250000e+01, 5.4250000e+01, 4.5250000e+01]
        Tolerance: 1.0000000e-06

**Comment by blowekamp** [comment]
Hello,

This repository is for packaging of SimpleITK for Python. Please report you issue to [SimpleITK/SimpleITK](https://github.com/SimpleITK/SimpleITK/issues)
