### ISSUE TITLE
update SimpleITK_GIT_PROTOCOL to https

### ISSUE THREAD

**Issue by hubutui** [SimpleITK/SimpleITKPythonPackage#49]
According to https://github.blog/2021-09-01-improving-git-protocol-security-github/,
> Only users connecting via SSH or git:// are affected. If your Git remotes start with https://, nothing in this post will affect you. If you’re an SSH user, read on for the details and timeline.

https://github.com/SimpleITK/SimpleITKPythonPackage/blob/eccf25af9bce588ba01d974089a41c48ac1c6bba/CMakeLists.txt#L128

**Comment by blowekamp** [comment]
addressed in #50 
Also v2.1.1.1 source has been uploaded to PyPi with the fix.
