### ISSUE TITLE
Integrate change into upstream SimpleITK

### ISSUE THREAD

**Issue by jcfr** [SimpleITK/SimpleITKPythonPackage#7]
See https://github.com/SimpleITK/SimpleITK/compare/master...jcfr:simplify-python-packaging-rebased

**Comment by jcfr** [comment]
Cc: @blowekamp

**Comment by blowekamp** [comment]
The changes look pretty good. Can you make 3 pull request?
 
1. Python packaging
2. targetLinkLibrariesWithDynamicLookup
3. Other fix ups

I expect 3 to quickly go in, a little testing for 2, and a review of goals and requirements of nightly builds for number 1.

**Comment by blowekamp** [comment]
@jcfr 
Began integrating patches...
https://github.com/SimpleITK/SimpleITK/commit/d8831bf553d6788dfa5b86472a0138e42e75dd8c
These TERMINAL options to ExternalProject appear to have been introduced in CMake 3.4.  With CMake 3.2 we are getting the following configuration errors:
https://open.cdash.org/viewConfigure.php?buildid=4653904

And with commenting out the one offending line we then get a some other errors of the following form:CMake Error at /Applications/CMake.app/Contents/share/cmake-3.2/Modules/ExternalProject.cmake:2027 (get_property):
  get_property could not find TARGET USES_TERMINAL_CONFIGURE.  Perhaps it has
  not yet been created.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.2/Modules/ExternalProject.cmake:2324 (_ep_add_configure_command)
  External_PCRE.cmake:39 (ExternalProject_add)
  External_Swig.cmake:68 (include)
  SuperBuild.cmake:309 (include)
  CMakeLists.txt:24 (include)

**Comment by blowekamp** [comment]
@jcfr  Do you have any suggestions with integrating these first couple of changes?

**Comment by jcfr** [comment]
@blowekamp Thanks for the comments and suggestions, I will follow asap with an updated SimpleITK PRs.

**Comment by blowekamp** [comment]
I made the following follow up commits:
https://github.com/SimpleITK/SimpleITK/commit/6ca10ab652efdc105f5d8b77df4c3b190c11eca1
https://github.com/SimpleITK/SimpleITK/commit/767793458de41d46b7d3a585889a3cbb24f948e5

The issue on the dashboard is now cleared up. I will merged those couple patches into master. Review of the changes is encouraged.

**Comment by jcfr** [comment]
Thanks @blowekamp , looks good :+1:

**Comment by blowekamp** [comment]
I have gone a github pull request of  the integration of the scikit-build version of dynamic lookup make module:
https://github.com/SimpleITK/SimpleITK/pull/80

**Comment by blowekamp** [comment]
The update to the Python packaging commit is the last outstanding contribution. The original patch has been cherry-picked on to the current master here, and a pull request made here.
SimpleITK/SimpleITK#84

**Comment by blowekamp** [comment]
All related topics have been merged into SimpleITK master.
